// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdwufnckoahubztohrgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkd3VmbmNrb2FodWJ6dG9ocmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTQ5NzYsImV4cCI6MjA1NTg3MDk3Nn0.aWpLU-gY009uBU-IDjk8WGcpnVrJEKP9vK78OP1Gilk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);